---
- name: Configure Docker on Deployserver
  hosts: all
  become: true
  tasks:
  - name: apt updating
    command: sudo apt update
  - name: Install python and Pip
    command: sudo apt install -y python3-pip
  - name: start docker service using systemctl
    command: sudo systemctl start docker
    become: yes
    become_user: root
  - name: Deploy the Image from DockerHub and Run as Container
    command: docker run -itd -p 8084:8081 augustine325/finance-me:1.0
