---
- name: Configure Docker on Deployserver
  hosts: all
  become: true
  tasks:

  - name: Install python and Pip
    command: sudo apt install -y python3-pip
  
  - name: start docker service using systemctl
    command: sudo systemctl start docker
    become: yes
    become_user: root
  - name: Deploy the Image from DockerHub and Run as Container
    command: docker run -itd -p 8082:8091 augustine325/endtoendproject31july:v1
